
services:
  - type: web
    name: bci-ritual-game
    env: node
    plan: starter
    buildCommand: npm run build:render
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bci-game-db
          property: connectionString
    healthCheckPath: /
